//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetSessionWebServ2.GlobalRessources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AdminPanelRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AdminPanelRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProjetSessionWebServ2.GlobalRessources.AdminPanelRes", typeof(AdminPanelRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conférences.
        /// </summary>
        public static string Conferences {
            get {
                return ResourceManager.GetString("Conferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Créer Conférences.
        /// </summary>
        public static string CreateConferences {
            get {
                return ResourceManager.GetString("CreateConferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Créer un congrès.
        /// </summary>
        public static string CreateCongres {
            get {
                return ResourceManager.GetString("CreateCongres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Créer Types Événements.
        /// </summary>
        public static string CreateEventTypes {
            get {
                return ResourceManager.GetString("CreateEventTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Créer Kiosques.
        /// </summary>
        public static string CreateKiosk {
            get {
                return ResourceManager.GetString("CreateKiosk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Créer Autres Événements.
        /// </summary>
        public static string CreateOtherEvents {
            get {
                return ResourceManager.GetString("CreateOtherEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Créer Salles.
        /// </summary>
        public static string CreateRooms {
            get {
                return ResourceManager.GetString("CreateRooms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Créer Sections.
        /// </summary>
        public static string CreateSections {
            get {
                return ResourceManager.GetString("CreateSections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Créer Spectacles.
        /// </summary>
        public static string CreateShows {
            get {
                return ResourceManager.GetString("CreateShows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Créer Tournois.
        /// </summary>
        public static string CreateTournaments {
            get {
                return ResourceManager.GetString("CreateTournaments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Créer Type Conferences.
        /// </summary>
        public static string CreateTypeConferences {
            get {
                return ResourceManager.GetString("CreateTypeConferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Créer Type Kiosques.
        /// </summary>
        public static string CreateTypeKiosques {
            get {
                return ResourceManager.GetString("CreateTypeKiosques", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Créer Type Spectacles.
        /// </summary>
        public static string CreateTypeShows {
            get {
                return ResourceManager.GetString("CreateTypeShows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Créer Type Tournois.
        /// </summary>
        public static string CreateTypeTournaments {
            get {
                return ResourceManager.GetString("CreateTypeTournaments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index Conférences.
        /// </summary>
        public static string IndexConferences {
            get {
                return ResourceManager.GetString("IndexConferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index type d&apos;événements.
        /// </summary>
        public static string IndexEventTypes {
            get {
                return ResourceManager.GetString("IndexEventTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index Kiosques.
        /// </summary>
        public static string IndexKiosk {
            get {
                return ResourceManager.GetString("IndexKiosk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index Autres Événements.
        /// </summary>
        public static string IndexOtherEvents {
            get {
                return ResourceManager.GetString("IndexOtherEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index Salles.
        /// </summary>
        public static string IndexRooms {
            get {
                return ResourceManager.GetString("IndexRooms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index Sections.
        /// </summary>
        public static string IndexSections {
            get {
                return ResourceManager.GetString("IndexSections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index Spectacles.
        /// </summary>
        public static string IndexShows {
            get {
                return ResourceManager.GetString("IndexShows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index Tournois.
        /// </summary>
        public static string IndexTournaments {
            get {
                return ResourceManager.GetString("IndexTournaments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index type Conferences.
        /// </summary>
        public static string IndexTypeConferences {
            get {
                return ResourceManager.GetString("IndexTypeConferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index type Kiosques.
        /// </summary>
        public static string IndexTypeKiosques {
            get {
                return ResourceManager.GetString("IndexTypeKiosques", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index type Spectacles.
        /// </summary>
        public static string IndexTypeShows {
            get {
                return ResourceManager.GetString("IndexTypeShows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index type Tournois.
        /// </summary>
        public static string IndexTypeTournaments {
            get {
                return ResourceManager.GetString("IndexTypeTournaments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kiosques.
        /// </summary>
        public static string Kiosk {
            get {
                return ResourceManager.GetString("Kiosk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autres Événements.
        /// </summary>
        public static string OtherEvents {
            get {
                return ResourceManager.GetString("OtherEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salle.
        /// </summary>
        public static string Rooms {
            get {
                return ResourceManager.GetString("Rooms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rapport des ventes.
        /// </summary>
        public static string SalesReport {
            get {
                return ResourceManager.GetString("SalesReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sections.
        /// </summary>
        public static string Sections {
            get {
                return ResourceManager.GetString("Sections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spectacles.
        /// </summary>
        public static string Shows {
            get {
                return ResourceManager.GetString("Shows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tournois.
        /// </summary>
        public static string Tournaments {
            get {
                return ResourceManager.GetString("Tournaments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Panneau d&apos;administration.
        /// </summary>
        public static string ViewName {
            get {
                return ResourceManager.GetString("ViewName", resourceCulture);
            }
        }
    }
}
