//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetSessionWebServ2.GlobalRessources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TournoiRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TournoiRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProjetSessionWebServ2.GlobalRessources.TournoiRes", typeof(TournoiRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to À.
        /// </summary>
        public static string A {
            get {
                return ResourceManager.GetString("A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actif.
        /// </summary>
        public static string Actif {
            get {
                return ResourceManager.GetString("Actif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ajouter une partie.
        /// </summary>
        public static string AjouterPartie {
            get {
                return ResourceManager.GetString("AjouterPartie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ajouteur une partie au Tournoi.
        /// </summary>
        public static string AjouterUnePartieTournoi {
            get {
                return ResourceManager.GetString("AjouterUnePartieTournoi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annulée.
        /// </summary>
        public static string Annulee {
            get {
                return ResourceManager.GetString("Annulee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annuler.
        /// </summary>
        public static string Annuler {
            get {
                return ResourceManager.GetString("Annuler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voulez-vous vraiment supprimer ceci?.
        /// </summary>
        public static string AreYouSureYouWantToDeleteThis {
            get {
                return ResourceManager.GetString("AreYouSureYouWantToDeleteThis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revenir  à la liste.
        /// </summary>
        public static string BackToList {
            get {
                return ResourceManager.GetString("BackToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choisir comme gagnant.
        /// </summary>
        public static string ChoisirCommeGagnant {
            get {
                return ResourceManager.GetString("ChoisirCommeGagnant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choisir un gagnant....
        /// </summary>
        public static string ChoisirGagnant {
            get {
                return ResourceManager.GetString("ChoisirGagnant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classement.
        /// </summary>
        public static string Classement {
            get {
                return ResourceManager.GetString("Classement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Créer.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Créer nouveau.
        /// </summary>
        public static string CreateNew {
            get {
                return ResourceManager.GetString("CreateNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Créer l&apos;équipe et joindre le tournoi.
        /// </summary>
        public static string CreateTeamAndJoin {
            get {
                return ResourceManager.GetString("CreateTeamAndJoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Créer une partie.
        /// </summary>
        public static string CreerPartie {
            get {
                return ResourceManager.GetString("CreerPartie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date et Heure.
        /// </summary>
        public static string DateHeure {
            get {
                return ResourceManager.GetString("DateHeure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date de la partie.
        /// </summary>
        public static string DatePartie {
            get {
                return ResourceManager.GetString("DatePartie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date du tournoi.
        /// </summary>
        public static string DateTournoi {
            get {
                return ResourceManager.GetString("DateTournoi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Definir un gagnant.
        /// </summary>
        public static string DefinirGagnant {
            get {
                return ResourceManager.GetString("DefinirGagnant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choisissez un gagnant pour cette partie.
        /// </summary>
        public static string DefinirGagnantTexte {
            get {
                return ResourceManager.GetString("DefinirGagnantTexte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Déjà participant.
        /// </summary>
        public static string DejaParticipant {
            get {
                return ResourceManager.GetString("DejaParticipant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Il semblerait que vous soyez déjà un participant dans une équipe de ce tournois. Vous ne pouvez participer qu&apos;une seule fois dans un tournois..
        /// </summary>
        public static string DejaParticipantTexte {
            get {
                return ResourceManager.GetString("DejaParticipantTexte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suprimmer.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Détails.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Détails pour une Équipe.
        /// </summary>
        public static string DetailsPourEquipe {
            get {
                return ResourceManager.GetString("DetailsPourEquipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Détails pour l&apos;équipe.
        /// </summary>
        public static string DetailsPourLequipe {
            get {
                return ResourceManager.GetString("DetailsPourLequipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Édit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entrez vos équipes ici, séparés par des virgules.
        /// </summary>
        public static string EnterTeamsPlaceholder {
            get {
                return ResourceManager.GetString("EnterTeamsPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Équipe.
        /// </summary>
        public static string Equipe {
            get {
                return ResourceManager.GetString("Equipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Équipes.
        /// </summary>
        public static string Equipes {
            get {
                return ResourceManager.GetString("Equipes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liste des équipes du Tournoi.
        /// </summary>
        public static string EquipesTournois {
            get {
                return ResourceManager.GetString("EquipesTournois", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Êtes vous sûr de vouloir participer au tournoi avec cette équipe?.
        /// </summary>
        public static string EtesVousSurParticiper {
            get {
                return ResourceManager.GetString("EtesVousSurParticiper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gagnant.
        /// </summary>
        public static string Gagnant {
            get {
                return ResourceManager.GetString("Gagnant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heure de début.
        /// </summary>
        public static string HeureDebut {
            get {
                return ResourceManager.GetString("HeureDebut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heure de fin.
        /// </summary>
        public static string HeureFin {
            get {
                return ResourceManager.GetString("HeureFin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Joindre avec une nouvelle équipe.
        /// </summary>
        public static string JoinAsNewTeam {
            get {
                return ResourceManager.GetString("JoinAsNewTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Joindre l&apos;équipe.
        /// </summary>
        public static string JoindreEquipe {
            get {
                return ResourceManager.GetString("JoindreEquipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Joueur.
        /// </summary>
        public static string Joueur {
            get {
                return ResourceManager.GetString("Joueur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Joueurs.
        /// </summary>
        public static string Joueurs {
            get {
                return ResourceManager.GetString("Joueurs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Membres de l&apos;équipe.
        /// </summary>
        public static string MembresEquipe {
            get {
                return ResourceManager.GetString("MembresEquipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom.
        /// </summary>
        public static string Nom {
            get {
                return ResourceManager.GetString("Nom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tournoi.
        /// </summary>
        public static string NomController {
            get {
                return ResourceManager.GetString("NomController", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom de l&apos;équipe.
        /// </summary>
        public static string NomEquipe {
            get {
                return ResourceManager.GetString("NomEquipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom du tournoi.
        /// </summary>
        public static string NomTournoi {
            get {
                return ResourceManager.GetString("NomTournoi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oups!.
        /// </summary>
        public static string Oups {
            get {
                return ResourceManager.GetString("Oups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Par nom.
        /// </summary>
        public static string ParNom {
            get {
                return ResourceManager.GetString("ParNom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Par participant.
        /// </summary>
        public static string ParParticipant {
            get {
                return ResourceManager.GetString("ParParticipant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Participer.
        /// </summary>
        public static string Participate {
            get {
                return ResourceManager.GetString("Participate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partie.
        /// </summary>
        public static string Partie {
            get {
                return ResourceManager.GetString("Partie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parties du Tournoi.
        /// </summary>
        public static string PartiesTournoi {
            get {
                return ResourceManager.GetString("PartiesTournoi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Par type de tournoi.
        /// </summary>
        public static string ParTypeTournoi {
            get {
                return ResourceManager.GetString("ParTypeTournoi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pointage.
        /// </summary>
        public static string Pointage {
            get {
                return ResourceManager.GetString("Pointage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rang.
        /// </summary>
        public static string Rang {
            get {
                return ResourceManager.GetString("Rang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rechercher.
        /// </summary>
        public static string Rechercher {
            get {
                return ResourceManager.GetString("Rechercher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retour aux Parties du Tournoi.
        /// </summary>
        public static string RetourAuPartiesTournoi {
            get {
                return ResourceManager.GetString("RetourAuPartiesTournoi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retour au tournoi.
        /// </summary>
        public static string RetourAuTournoi {
            get {
                return ResourceManager.GetString("RetourAuTournoi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retour à l&apos;index des Tournois.
        /// </summary>
        public static string RetourIndexTournois {
            get {
                return ResourceManager.GetString("RetourIndexTournois", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sauvegarder.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statut du Tournoi.
        /// </summary>
        public static string StatutTournoi {
            get {
                return ResourceManager.GetString("StatutTournoi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Équipe qui participe.
        /// </summary>
        public static string TeamParticipating {
            get {
                return ResourceManager.GetString("TeamParticipating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trier par type de tournoi.
        /// </summary>
        public static string TrierParTypeDeTournoi {
            get {
                return ResourceManager.GetString("TrierParTypeDeTournoi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type de tournoi.
        /// </summary>
        public static string TypeTournoi {
            get {
                return ResourceManager.GetString("TypeTournoi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voir les parties du tournoi.
        /// </summary>
        public static string VoirPartiesTournoi {
            get {
                return ResourceManager.GetString("VoirPartiesTournoi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voir le statut du tournoi.
        /// </summary>
        public static string VoirStatutTournoi {
            get {
                return ResourceManager.GetString("VoirStatutTournoi", resourceCulture);
            }
        }
    }
}
